import js from '@eslint/js';
import prettier from 'eslint-config-prettier';

export default [
  js.configs.recommended,
  prettier,
  {
    ignores: ['dist/**', 'node_modules/**', '**/*.min.js', 'coverage/**'],
  },
  {
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        console: 'readonly',
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        FileReader: 'readonly',
        Worker: 'readonly',
        CustomEvent: 'readonly',
        EventTarget: 'readonly',
        localStorage: 'readonly',
        performance: 'readonly',
        ArrayBuffer: 'readonly',
        Uint8Array: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        URL: 'readonly',
        FormData: 'readonly',
        import: 'readonly',
        process: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        global: 'readonly',
        self: 'readonly',
        vi: 'readonly',
        describe: 'readonly',
        it: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        test: 'readonly',
        Event: 'readonly',
        KeyboardEvent: 'readonly',
        MouseEvent: 'readonly',
        fetch: 'readonly',
        table: 'readonly',
        ReadableStream: 'readonly',
        WritableStream: 'readonly',
        TextDecoder: 'readonly',
        TextEncoder: 'readonly',
        AsyncIterator: 'readonly',
        HTMLImageElement: 'readonly',
        HTMLCanvasElement: 'readonly',
        HTMLVideoElement: 'readonly',
        ImageData: 'readonly',
        Image: 'readonly',
        AbortController: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        matchMedia: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      'prefer-const': 'error',
      'no-var': 'error',
      'no-prototype-builtins': 'off',
    },
  },
];
